export type baseSceneT = {
  _id?: string
  version?: string
  id: number
  name: string
  desc: string
  name_zh?: string
  desc_zh?: string
  name_ko?: string
  desc_ko?: string
  name_de?: string
  desc_de?: string
  name_fr?: string
  desc_fr?: string
  name_ja?: string
  desc_ja?: string
  name_es?: string
  desc_es?: string
  authorName: string
  is3D: boolean
  isSky: boolean
  iconPath: string
  modelPath: string
  textureName: string
  packageName: string
  pageViews: number
  installCount: number
  packageSize: string
  apkName: string
  isNew: boolean
  tagList: number[]
  sortIndex: number
}
